services:
  nextchat:
    container_name: interviewSheep
    image: coderunxiaoming/nextchat_interview
    ports:
      - 3000:3000
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      CODE: ${CODE}
      BASE_URL: ${BASE_URL}

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - nextchat